version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    ports:
      - "4040:4040"
